package com.esde.companion.ui.settings

import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import com.esde.companion.AppContainer

class SettingsViewModelFactory(
    private val appContainer: AppContainer,
) : ViewModelProvider.Factory {
    @Suppress("UNCHECKED_CAST")
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        require(modelClass.isAssignableFrom(SettingsViewModel::class.java)) {
            "Unknown ViewModel class: $modelClass"
        }
        return SettingsViewModel(
            onboardingRepository = appContainer.onboardingRepository,
            validateLogFolderUseCase = appContainer.validateEsdeLogFolderUseCase,
            validateMediaFolderUseCase = appContainer.validateEsdeMediaFolderUseCase,
            observeGamePlayingBehaviorUseCase = appContainer.observeGamePlayingBehaviorUseCase,
            setGamePlayingBehaviorUseCase = appContainer.setGamePlayingBehaviorUseCase,
            observeGamePlayingDimPercentUseCase = appContainer.observeGamePlayingDimPercentUseCase,
            setGamePlayingDimPercentUseCase = appContainer.setGamePlayingDimPercentUseCase,
            observeScreensaverBehaviorUseCase = appContainer.observeScreensaverBehaviorUseCase,
            setScreensaverBehaviorUseCase = appContainer.setScreensaverBehaviorUseCase,
            observeScreensaverDimPercentUseCase = appContainer.observeScreensaverDimPercentUseCase,
            setScreensaverDimPercentUseCase = appContainer.setScreensaverDimPercentUseCase,
            observeThemePreferenceUseCase = appContainer.observeThemePreferenceUseCase,
            setThemePreferenceUseCase = appContainer.setThemePreferenceUseCase,
            observeOverlayOpacityUseCase = appContainer.observeOverlayOpacityUseCase,
            setOverlayOpacityUseCase = appContainer.setOverlayOpacityUseCase,
            observeGridColumnsUseCase = appContainer.observeGridColumnsUseCase,
            setGridColumnsUseCase = appContainer.setGridColumnsUseCase,
            observeSortFoldersOnTopUseCase = appContainer.observeSortFoldersOnTopUseCase,
            setSortFoldersOnTopUseCase = appContainer.setSortFoldersOnTopUseCase,
            observeShowSearchBarUseCase = appContainer.observeShowSearchBarUseCase,
            setShowSearchBarUseCase = appContainer.setShowSearchBarUseCase,
            observeDockEnabledUseCase = appContainer.observeDockEnabledUseCase,
            setDockEnabledUseCase = appContainer.setDockEnabledUseCase,
            observeDockMaxAppsUseCase = appContainer.observeDockMaxAppsUseCase,
            setDockMaxAppsUseCase = appContainer.setDockMaxAppsUseCase,
            observeDockSizeUseCase = appContainer.observeDockSizeUseCase,
            setDockSizeUseCase = appContainer.setDockSizeUseCase,
            observeMusicEnabledUseCase = appContainer.observeMusicEnabledUseCase,
            setMusicEnabledUseCase = appContainer.setMusicEnabledUseCase,
            observeMusicPlayWhileBrowsingSystemsUseCase = appContainer.observeMusicPlayWhileBrowsingSystemsUseCase,
            setMusicPlayWhileBrowsingSystemsUseCase = appContainer.setMusicPlayWhileBrowsingSystemsUseCase,
            observeMusicPlayWhileBrowsingGamesUseCase = appContainer.observeMusicPlayWhileBrowsingGamesUseCase,
            setMusicPlayWhileBrowsingGamesUseCase = appContainer.setMusicPlayWhileBrowsingGamesUseCase,
            observeMusicPlayDuringScreensaverUseCase = appContainer.observeMusicPlayDuringScreensaverUseCase,
            setMusicPlayDuringScreensaverUseCase = appContainer.setMusicPlayDuringScreensaverUseCase,
            observeMusicDuckingModeUseCase = appContainer.observeMusicDuckingModeUseCase,
            setMusicDuckingModeUseCase = appContainer.setMusicDuckingModeUseCase,
            observeCloseCompanionOnQuitEnabledUseCase = appContainer.observeCloseCompanionOnQuitEnabledUseCase,
            setCloseCompanionOnQuitEnabledUseCase = appContainer.setCloseCompanionOnQuitEnabledUseCase,
            observeFabAssignmentsUseCase = appContainer.observeFabAssignmentsUseCase,
            setFabAssignmentUseCase = appContainer.setFabAssignmentUseCase,
            setBluetoothPermissionRequestedUseCase = appContainer.setBluetoothPermissionRequestedUseCase,
            notifyBluetoothPermissionRecheck = appContainer.bluetoothPermissionRecheckSignal::notifyChanged,
            observeInstalledAppsUseCase = appContainer.observeInstalledAppsUseCase,
            observeLaunchEsdeOnStartEnabledUseCase = appContainer.observeLaunchEsdeOnStartEnabledUseCase,
            setLaunchEsdeOnStartEnabledUseCase = appContainer.setLaunchEsdeOnStartEnabledUseCase,
            observeDebugLoggingEnabledUseCase = appContainer.observeDebugLoggingEnabledUseCase,
            setDebugLoggingEnabledUseCase = appContainer.setDebugLoggingEnabledUseCase,
            exportConfigBackupUseCase = appContainer.exportConfigBackupUseCase,
            restoreConfigBackupUseCase = appContainer.restoreConfigBackupUseCase,
            observeRetroAchievementsCredentialsUseCase = appContainer.observeRetroAchievementsCredentialsUseCase,
            validateRetroAchievementsCredentialsUseCase = appContainer.validateRetroAchievementsCredentialsUseCase,
            clearRetroAchievementsCredentialsUseCase = appContainer.clearRetroAchievementsCredentialsUseCase,
            observeUpdateOnScreensaverUseCase = appContainer.observeUpdateAchievementsOnScreensaverEnabledUseCase,
            setUpdateOnScreensaverUseCase = appContainer.setUpdateAchievementsOnScreensaverEnabledUseCase,
            observeLidWakeGuardEnabledUseCase = appContainer.observeLidWakeGuardEnabledUseCase,
            setLidWakeGuardEnabledUseCase = appContainer.setLidWakeGuardEnabledUseCase,
            observeHallSensorCalibrationUseCase = appContainer.observeHallSensorCalibrationUseCase,
            setHallSensorCalibrationUseCase = appContainer.setHallSensorCalibrationUseCase,
            observeAutoFpsEnabledUseCase = appContainer.observeAutoFpsEnabledUseCase,
            setAutoFpsEnabledUseCase = appContainer.setAutoFpsEnabledUseCase,
            observeTaskKillerEnabledUseCase = appContainer.observeTaskKillerEnabledUseCase,
            setTaskKillerEnabledUseCase = appContainer.setTaskKillerEnabledUseCase,
            observeTaskKillerTargetUseCase = appContainer.observeTaskKillerTargetUseCase,
            setTaskKillerTargetUseCase = appContainer.setTaskKillerTargetUseCase,
            observeVolumeSyncEnabledUseCase = appContainer.observeVolumeSyncEnabledUseCase,
            setVolumeSyncEnabledUseCase = appContainer.setVolumeSyncEnabledUseCase,
            observeVolumeSyncModeUseCase = appContainer.observeVolumeSyncModeUseCase,
            setVolumeSyncModeUseCase = appContainer.setVolumeSyncModeUseCase,
            observeGameLaunchDisplayTargetUseCase = appContainer.observeGameLaunchDisplayTargetUseCase,
            setGameLaunchDisplayTargetUseCase = appContainer.setGameLaunchDisplayTargetUseCase,
            observeCloseAppOnGameEndUseCase = appContainer.observeCloseAppOnGameEndUseCase,
            setCloseAppOnGameEndUseCase = appContainer.setCloseAppOnGameEndUseCase,
            observeGameLaunchEnabledUseCase = appContainer.observeGameLaunchEnabledUseCase,
            setGameLaunchEnabledUseCase = appContainer.setGameLaunchEnabledUseCase,
            deleteAllGameGuidesUseCase = appContainer.deleteAllGameGuidesUseCase,
            observeManualFallbackOnNoGuideEnabledUseCase = appContainer.observeManualFallbackOnNoGuideEnabledUseCase,
            setManualFallbackOnNoGuideEnabledUseCase = appContainer.setManualFallbackOnNoGuideEnabledUseCase,
            volumeSyncSecondarySettingPresent = appContainer.volumeSyncSecondarySettingPresent,
        ) as T
    }
}
